# COMMANDS (node anchors)
.create_directories: &create-directories
    desc: Create directories
    cmd: '
    ([ -d ../../shared/public/uploads/acts ] || mkdir -p ../../shared/public/uploads)'

.opcache_reset: &opcache-reset-production
    desc: Clearing opcache
    cmd: 'curl https://milan.inventisstage.be/opcache_reset.php'

# DEFAULT ENVIRONMENT CONFIG
.environment: &environment-defaults
    user: inventisstagebe
    from: ./
    releases: 2
    hosts:
        - ssh038.webhosting.be

# SETUP
magephp:
    exclude:
        - ./public/uploads
        - ./docker
        - ./node_modules
        - ./mage_logs
        - ./**/.gitignore
        - ./**/node_modules
        - ./**/.DS_Store
        - ./.env
        - ./.editorconfig
        - ./.idea
        - ./.gitignore
        - ./.Mage.yml
        - ./.php-version.yml
        - ./symfony.lock
        - ./package.json
        - ./.phpstorm.meta.php
        - ./bitbucket-pipelines.yml
        - ./composer.lock
        - ./docker-compose.yml
        - ./docker-compose.yml.dist
        - ./README.md
        - ./vendor/andres-montanez
        - ./vendor/**/doc
        - ./vendor/**/docs
        - ./vendor/**/bin
        - ./vendor/**/tests
        - ./vendor/**/*.md
        - ./vendor/**/LICENSE
        - ./tests
    log_dir: ./var/Mage-logs
    environments:
        production:
            <<: *environment-defaults
            symfony:
                env: 'prod'
                console: 'php8.2 bin/console'
            host_path: /data/sites/web/inventisstagebe/subsites/milan.inventissstage.be
            on-deploy:
                -   exec: *create-directories
                -   fs/link: { from: '../../../shared/public/uploads', to: 'public/uploads' }
                -   fs/link: { from: '../../shared/.env', to: '.env' }
                -   fs/link: { from: '../../../shared/public/cache', to: 'public/cache' }
                -   symfony/cache-warmup: { flags: '--no-debug' }
                -   console: { command: 'doctrine:migrations:migrate --allow-no-migration --no-interaction' }
            post-release:
                -   exec: *opcache-reset-production

    custom_tasks:
        - 'App\Mage\ConsoleTask'
