<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZiZw8T6\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZiZw8T6/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZiZw8T6.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZiZw8T6\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZiZw8T6\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZiZw8T6',
    'container.build_id' => 'd679baae',
    'container.build_time' => 1680859252,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZiZw8T6');
